channels:
  - conda-forge
dependencies:
  - gdal=3.8.5  
  - h5py=3.13.0
  - matplotlib=3.10.1
  - numpy=2.2.4
  - pip=25.0.1
  - python=3.11.10
  - scipy=1.15.2
  - pip:
      - ray==2.44.0
      - spectral==0.23.1